/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewerRouteImport } from './routes/reviewer'
import { Route as JournalHistoryRouteImport } from './routes/journal.history'
import { Route as JournalNewRouteImport } from './routes/journal.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerRoute = ReviewerRouteImport.update({
  id: '/reviewer',
  path: '/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalHistoryRoute = JournalHistoryRouteImport.update({
  id: '/journal/history',
  path: '/journal/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalNewRoute = JournalNewRouteImport.update({
  id: '/journal/new',
  path: '/journal/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reviewer': typeof ReviewerRoute
  '/journal/history': typeof JournalHistoryRoute
  '/journal/new': typeof JournalNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reviewer': typeof ReviewerRoute
  '/journal/history': typeof JournalHistoryRoute
  '/journal/new': typeof JournalNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reviewer': typeof ReviewerRoute
  '/journal/history': typeof JournalHistoryRoute
  '/journal/new': typeof JournalNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reviewer' | '/journal/history' | '/journal/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reviewer' | '/journal/history' | '/journal/new'
  id: '__root__' | '/' | '/reviewer' | '/journal/history' | '/journal/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewerRoute: typeof ReviewerRoute
  JournalHistoryRoute: typeof JournalHistoryRoute
  JournalNewRoute: typeof JournalNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer': {
      id: '/reviewer'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof ReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/history': {
      id: '/journal/history'
      path: '/journal/history'
      fullPath: '/journal/history'
      preLoaderRoute: typeof JournalHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/new': {
      id: '/journal/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof JournalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewerRoute: ReviewerRoute,
  JournalHistoryRoute: JournalHistoryRoute,
  JournalNewRoute: JournalNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
